<NumpadButton@Button>
    background_normal: ""
    background_color: "#8f8f8f"
    font_size: "24sp"

<OpButton@NumpadButton>
    background_color: "#4f4f4f"

<MyCalc>:
    BoxLayout:
        orientation: "horizontal"

        size_hint: 1, 0.20

        Label:
            size_hint_x: 0.80

            font_size: "32sp"

            text_size: self.size
            padding_x: "20dp"
            halign: "right"
            valign: "middle"

            text: root.result

    GridLayout:
        id: numpad

        rows:    5
        cols:    4
        spacing: 1

        size_hint: 1, 0.90

        OpButton:
            text: "("
            on_release: root.left_bracket()
        OpButton:
            text: ")"
            on_release: root.right_bracket()

        OpButton:
            text: "<-"
            on_release: root.backspace()

        OpButton:
            text: "C"
            on_release: root.clear()

        # Numpad
        NumpadButton:           
            text: "1"
            on_release: root.one(self)
        NumpadButton: 
            text: "2"
            on_release: root.two()
        NumpadButton: 
            text: "3"
            on_release: root.three()

        OpButton: 
            text: "÷"
            on_release: root.div()

        NumpadButton: 
            text: "4"
            on_release: root.four()
        NumpadButton: 
            text: "5"
            on_release: root.five()
        NumpadButton: 
            text: "6"
            on_release: root.six()

        OpButton: 
            text: "×"
            on_release: root.mult()

        NumpadButton: 
            text: "7"
            on_release: root.seven()
        NumpadButton: 
            text: "8"
            on_release: root.eight()
        NumpadButton: 
            text: "9"
            on_release: root.nine()

        OpButton: 
            text: "-"
            on_release: root.minus()

        NumpadButton: 
            text: "."
            on_release: root.point()
        NumpadButton: 
            text: "0"
            on_release: root.zero()
        OpButton: 
            background_color: "#CC6633"
            text: "="
            on_release: root.equals()

        OpButton: 
            text: "+"
            on_release: root.plus()
              